### ISSUE TITLE
Warning and error underlines appear behind text

### ISSUE THREAD

**Issue by nhristova** [wesbos/cobalt2-vscode#249] opened 2024-04-22 09:12 UTC
## Description

The squiggly lines indicating errors and warnings appear very close (even behind) the text. I tried modifying the line height and that improves the appearance a bit. However, when I switch the theme to Visual Studio Dark, even with line height set to 0, the underline is not that close (attached images below). Switched fonts, that didn't change anything. 
I was not able to find another setting to modify this distance. Is there a way to change it?

Cobalt2
![image](https://github.com/wesbos/cobalt2-vscode/assets/19491111/1de8ca3d-c898-4fa1-a259-377a4bb5e7b9)

Visual Studio Dark
![image](https://github.com/wesbos/cobalt2-vscode/assets/19491111/20304489-02bc-4904-915c-ba5db949144e)

This is the config I use: 

```json
{
    "editor.fontLigatures": true,
    "cSpell.language": "en-GB,bg",
    "editor.fontFamily": "'Operator Mono Lig','Cascadia Code', 'JetBrains Mono', 'Fira Code', 'Victor Mono', Consolas, 'Courier New', monospace",
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "explorer.confirmDelete": false,
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.minimap.renderCharacters": false,
    "debug.showBreakpointsInOverviewRuler": true,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "javascript.updateImportsOnFileMove.enabled": "always",
    "gitlens.views.tags.files.layout": "tree",
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "prettier.arrowParens": "avoid",
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[scss]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.colorTheme": "Cobalt2",
    "editor.detectIndentation": false,
    "prettier.tabWidth": 4,
    "explorer.confirmDragAndDrop": false,
    "diffEditor.experimental.showMoves": true,
    "editor.guides.bracketPairs": true,
    "workbench.editor.wrapTabs": true,
    "window.zoomLevel": -0.5,
    "typescript.enablePromptUseWorkspaceTsdk": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}

```

**Comment by palashmon** [comment] 2024-04-22 09:24
Duplicate of #248

A fix for now: https://github.com/wesbos/cobalt2-vscode/issues/248#issuecomment-2059663397

**Closed** 2024-04-25 12:09 UTC
