### ISSUE TITLE
Unclosed compotent – following text difficult to see

### ISSUE THREAD

**Issue by glaszczyk** [wesbos/cobalt2-vscode#52] opened 2017-09-22 11:57 UTC
I noticed that when I create new component/tag and it is not closed (because I'm editing it) following text is marked error-like (see second `Checkbox` component on screenshot). Is it possible to make this red lighter, because now it is sometimes difficult to see (when charakters like `=` are next)
![unclosedcomponent](https://user-images.githubusercontent.com/16131329/30743371-97ab7378-9f9d-11e7-9e65-a687353eb37a.png)

**Comment by wesbos** [comment] 2017-09-22 20:44
thanks -this is annoying. Will fix it! 

Closing because it's a dupe of https://github.com/wesbos/cobalt2-vscode/issues/36

**Closed by wesbos** 2017-09-22 20:44 UTC
