### ISSUE TITLE
Fragmented background

### ISSUE THREAD

**Issue by hiddenman** [wesbos/cobalt2-vscode#156] opened 2020-02-18 09:41 UTC
Hi there,

Some themes, including Cobalt2, running on VS Code 1.42.1, have fragmented background everywhere (see the screenshot). Looks like VSCode changes background only around text, not the whole screen.
![Screenshot from 2020-02-18 11-41-02](https://user-images.githubusercontent.com/4009515/74723649-9daf0180-5243-11ea-9f75-1dc9f23be791.png)

**Comment by marcelluseasley** [comment] 2020-03-02 00:18
I agree. I am experiencing the same thing. It's a nice theme, but that will probably be a deal beaker or me.

**Comment by ak-kubaslabs** [comment] 2020-03-02 00:21
> I agree. I am experiencing the same thing. It's a nice theme, but that will probably be a deal beaker or me.

Hi,
I already discovered that the issue is not related to the theme itself. It's Electron on Linux problem.
Just run it as "code --disable-gpu" and everything will be OK.
Here is the link to my another issue where you can find the link to the first issue with this:
https://github.com/microsoft/vscode/issues/91638

**Comment by hiddenman** [comment] 2020-03-02 00:22
> I agree. I am experiencing the same thing. It's a nice theme, but that will probably be a deal beaker or me.
Hi,
I already discovered that the issue is not related to the theme itself. It's Electron on Linux problem.
Just run it as "code --disable-gpu" and everything will be OK.
Here is the link to my another issue where you can find the link to the first issue with this:
https://github.com/microsoft/vscode/issues/91638

**Comment by HellPie** [comment] 2020-04-29 13:15
This also happens on Windows for me on a 1440p display.

It happens with all color themes except the high contrast theme. It also appears to generate weird artifacts in some UI elements, like the search bar in settings. Disable hardware acceleration fixes the problem and judging by the change in brightness of the editor it might be related to HDR support on the monitor or some other weird rendering problem, likely tied to Electron more than Visual Studio Code but I didn't notice any issue with Discord Canary or Discord Stable builds and other Electron apps.

Disabling hardware acceleration has a noticeable drop in performance to the point where I can clearly see VSCode (and Discord too) struggling a lot to keep a stable framerate, with consistent drops, microlag and very, very annoying all-round janky UI.

Trying out the VSCode playground on the Azure-hosted website doesn't show the problem in Chrome 84 (I don't have other versions of Chrome installed) with hardware acceleration enabled.

![Annotation 2020-04-29 150617](https://user-images.githubusercontent.com/2611921/80599406-2b208600-8a2b-11ea-943b-dd15b2e7a314.png)
![Screenshot (11)](https://user-images.githubusercontent.com/2611921/80599413-2cea4980-8a2b-11ea-9afc-a207052647b9.png)
![Screenshot (12)](https://user-images.githubusercontent.com/2611921/80599417-2e1b7680-8a2b-11ea-9ef3-f196e3b009b3.png)
![Screenshot (13)](https://user-images.githubusercontent.com/2611921/80599428-32e02a80-8a2b-11ea-9057-1ff37159b724.png)
![Screenshot (14)](https://user-images.githubusercontent.com/2611921/80599439-3673b180-8a2b-11ea-993f-2b75335bd123.png)

**Comment by IllusionMH** [comment] 2020-07-06 10:02
There is an open issue for HDR on Windows and workaround described in https://github.com/microsoft/vscode/issues/88491#issuecomment-589527628.
As linked above - workaround for Linux will be https://github.com/microsoft/vscode/issues/85452#issuecomment-558334562

It doesn't looks like issues with partial background should be tracked in this repo.

**Comment by wesbos** [comment] 2020-11-27 20:14
thanks everyone - doesn't look like this is related to my theme, but VS code? Closing but feel free to reopen if i am wrong

**Closed by wesbos** 2020-11-27 20:14 UTC
